import { useEffect, useMemo, useRef, useState } from "react";
import { Bar,BarChart,CartesianGrid,Legend,Line,LineChart,ResponsiveContainer,Scatter,ScatterChart,Tooltip,XAxis,YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogTitle } from "@/components/ui/dialog";
import { compareObservation,exportSelectedCharts,getObservationGraphs,listObservationTypes,type ComparisonResult,type ObservationGraphs } from "@/services/observations";
import type { ObservationType } from "@/types/observation";
type Style="line"|"bar"|"points";type Mode="straight"|"comparison";type Config={typeId:string;mode:Mode;treatmentId:string;sessionId:string;sessionIds:string[];style:Style};
type Chart={title:string;subtitle:string;svg:string;columns:string[];rows:Array<Array<string|number|null>>;config:Config};
const colors=["#2fbfa9","#3978c5","#e29b3f","#9b62c7"];
const initial=(typeId=""):Config=>({typeId,mode:"straight",treatmentId:"",sessionId:"",sessionIds:[],style:"bar"});
const toggle=(values:string[],value:string)=>values.includes(value)?values.filter(item=>item!==value):[...values,value];
export default function ChartExportDialog({open,onOpenChange,projectId,initialTypeId}:{open:boolean;onOpenChange:(value:boolean)=>void;projectId:string;initialTypeId?:string}){
 const[types,setTypes]=useState<ObservationType[]>([]),[graphs,setGraphs]=useState<ObservationGraphs>(),[config,setConfig]=useState<Config>(initial(initialTypeId)),[comparison,setComparison]=useState<ComparisonResult>(),[charts,setCharts]=useState<Chart[]>([]),[error,setError]=useState("");const previewRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!open)return;listObservationTypes(projectId).then(items=>{const numeric=items.filter(item=>item.dataType==="number");setTypes(numeric);setConfig(current=>({...current,typeId:current.typeId||initialTypeId||numeric[0]?.id||""}))}).catch(reason=>setError(String(reason)))},[open,projectId,initialTypeId]);
 useEffect(()=>{if(!config.typeId)return;getObservationGraphs(projectId,config.typeId).then(data=>{setGraphs(data);setConfig(current=>({...current,sessionId:current.sessionId||data.sessions.at(-1)?.id||"",sessionIds:current.sessionIds.length?current.sessionIds:data.sessions.slice(-2).map(item=>item.id)}))}).catch(reason=>setError(String(reason)))},[projectId,config.typeId]);
 useEffect(()=>{if(config.mode!=="comparison"||!config.typeId||config.sessionIds.length<2){setComparison(undefined);return}compareObservation(projectId,config.typeId,{mode:"sessions",sessionIds:config.sessionIds,selectedTreatments:config.treatmentId?[`T${config.treatmentId}`]:undefined,groupBy:config.treatmentId?"plot":"treatment",aggregation:"average"}).then(setComparison).catch(reason=>setError(reason instanceof Error?reason.message:String(reason)))},[projectId,config.mode,config.sessionIds,config.treatmentId,config.typeId]);
 const preview=useMemo(()=>{if(!graphs)return{data:[] as Array<Record<string,string|number|null>>,keys:[] as string[],subtitle:""};if(config.mode==="comparison"&&comparison){const data=config.style==="line"?comparison.series.map(series=>({label:series.label,...Object.fromEntries(comparison.points.map(point=>[point.category,point.values[series.key]]))})):comparison.points.map(point=>({label:point.category,...point.values}));return{data,keys:config.style==="line"?comparison.points.map(point=>point.category):comparison.series.map(series=>series.key),subtitle:comparison.title}}const session=graphs.sessions.find(item=>item.id===config.sessionId)||graphs.sessions.at(-1);if(config.treatmentId){const series=graphs.timeSeries.filter(item=>item.treatmentId===config.treatmentId);return{data:series.map(item=>({label:item.replication,value:item.values.find(value=>value.sessionId===session?.id)?.value??null})),keys:["value"],subtitle:`T${config.treatmentId} replications · ${session?.label||"Session"}`}}return{data:(session?.compareTreatments||[]).map(item=>({label:item.treatment,value:item.average})),keys:["value"],subtitle:`Treatment overview · ${session?.label||"Session"}`}},[graphs,config,comparison]);
 const chart=config.style==="line"?<LineChart data={preview.data}><CartesianGrid strokeDasharray="4 4" opacity={.25}/><XAxis dataKey="label"/><YAxis/><Tooltip/><Legend/>{preview.keys.map((key,index)=><Line key={key} dataKey={key} stroke={colors[index%colors.length]} strokeWidth={3}/>)}</LineChart>:config.style==="points"?<ScatterChart><CartesianGrid strokeDasharray="4 4" opacity={.25}/><XAxis dataKey="label" type="category"/><YAxis/><Tooltip/><Legend/>{preview.keys.map((key,index)=><Scatter key={key} name={key} data={preview.data.map(row=>({label:row.label,value:row[key]}))} dataKey="value" fill={colors[index%colors.length]}/>)}</ScatterChart>:<BarChart data={preview.data}><CartesianGrid strokeDasharray="4 4" opacity={.25}/><XAxis dataKey="label"/><YAxis/><Tooltip/><Legend/>{preview.keys.map((key,index)=><Bar key={key} dataKey={key} fill={colors[index%colors.length]}/>)}</BarChart>;
 const add=()=>{const svg=previewRef.current?.querySelector("svg");if(!svg||!preview.data.length)return setError("Choose a valid configuration with data before adding the chart.");const columns=Object.keys(preview.data[0]);setCharts(current=>[...current,{title:types.find(item=>item.id===config.typeId)?.name||"Observation",subtitle:`${preview.subtitle} · ${config.style}`,svg:new XMLSerializer().serializeToString(svg),columns,rows:preview.data.map(row=>columns.map(column=>row[column]??null)),config:{...config}}]);setError("")};
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[94vh] overflow-y-auto sm:max-w-[920px]"><DialogTitle>Export Charts</DialogTitle><div className="grid gap-3 rounded-2xl border p-4 md:grid-cols-2"><select value={config.typeId} onChange={event=>setConfig(initial(event.target.value))}>{types.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><Choice values={["straight","comparison"]} value={config.mode} set={value=>setConfig(current=>({...current,mode:value as Mode}))}/><select value={config.treatmentId} onChange={event=>setConfig(current=>({...current,treatmentId:event.target.value}))}><option value="">Treatment overview</option>{graphs?.treatmentSeries.map(item=><option key={item.treatmentId} value={item.treatmentId}>{item.treatment} replications</option>)}</select>{config.mode==="straight"?<select value={config.sessionId} onChange={event=>setConfig(current=>({...current,sessionId:event.target.value}))}>{graphs?.sessions.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select>:<div className="flex flex-wrap gap-1">{graphs?.sessions.map(item=><button type="button" key={item.id} onClick={()=>setConfig(current=>({...current,sessionIds:toggle(current.sessionIds,item.id)}))} className={`rounded-full border px-2 py-1 ${config.sessionIds.includes(item.id)?"bg-primary text-primary-foreground":""}`}>{item.label}</button>)}</div>}<Choice values={["line","bar","points"]} value={config.style} set={value=>setConfig(current=>({...current,style:value as Style}))}/></div>{error&&<p className="text-destructive">{error}</p>}<div ref={previewRef} className="h-80 rounded-2xl border p-3"><ResponsiveContainer>{chart}</ResponsiveContainer></div><Button onClick={add}>Add this chart</Button>{charts.map((item,index)=><div key={index} className="rounded-xl border p-3"><b>{item.title}</b><small className="block text-muted-foreground">{item.subtitle}</small><Button variant="ghost" onClick={()=>setCharts(current=>current.filter((_,itemIndex)=>itemIndex!==index))}>Remove</Button></div>)}{!!charts.length&&<div className="flex gap-2">{(["png","pdf","xlsx"] as const).map(format=><Button key={format} onClick={()=>void exportSelectedCharts(projectId,format,format==="png"?[charts[0]]:charts)}>{format.toUpperCase()}</Button>)}</div>}</DialogContent></Dialog>;
}
function Choice({values,value,set}:{values:string[];value:string;set:(value:string)=>void}){return <div className="flex gap-1">{values.map(item=><button type="button" key={item} onClick={()=>set(item)} className={`rounded-full border px-3 py-2 ${value===item?"bg-primary text-primary-foreground":""}`}>{item}</button>)}</div>}
