import { useEffect, useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, Rectangle, ResponsiveContainer, Scatter, ScatterChart, XAxis, YAxis } from "recharts";
import { compareObservation, type ComparisonRequest, type ComparisonResult, type ObservationGraphs } from "@/services/observations";
import type { ObservationMeasurement, ObservationType } from "@/types/observation";
import type { ChartStyle } from ".";
import { InteractiveChart, selectHandlers, type ChartItemDetail } from "./ChartInteraction";

const colors=["#2fbfa9","#3978c5","#e29b3f","#9b62c7","#d35f78","#58756f","#ef7f45","#466eab","#79a84b","#a85d8c"];
const toggle=(values:string[],value:string)=>values.includes(value)?values.filter(x=>x!==value):[...values,value];
const nearestChartRow=(event:any,rows:Array<Record<string,any>>)=>{const native=event?.nativeEvent||event,target=native?.currentTarget||native?.target,root=target?.closest?.("[data-chart-root]");if(!root||!rows.length)return rows[0];const ticks=[...root.querySelectorAll(".recharts-xAxis .recharts-cartesian-axis-tick")];if(!ticks.length)return rows[0];const x=Number(native.clientX),index=ticks.reduce((best:number,tick:any,i:number)=>Math.abs(tick.getBoundingClientRect().left+tick.getBoundingClientRect().width/2-x)<Math.abs((ticks[best] as any).getBoundingClientRect().left+(ticks[best] as any).getBoundingClientRect().width/2-x)?i:best,0);return rows[Math.min(index,rows.length-1)]};
interface Props{projectId:string;type:ObservationType;records:ObservationMeasurement[];graphs:ObservationGraphs;chartStyle:ChartStyle;onSelectionChange:(request?:ComparisonRequest)=>void}

export default function ComparisonPanel({projectId,type,records,graphs,chartStyle,onSelectionChange}:Props){
  const dates=useMemo(()=>[...new Set(records.map(x=>x.capturedAt.slice(0,10)))].sort(),[records]);
  const treatments=useMemo(()=>[...new Set(records.map(x=>`T${x.treatment}`))].sort((a,b)=>Number(a.slice(1))-Number(b.slice(1))),[records]);
  const [mode,setMode]=useState<"sessions"|"dateRange">("sessions"),[sessionIds,setSessionIds]=useState<string[]>(graphs.sessions.slice(-2).map(x=>x.id)),[from,setFrom]=useState(dates[0]||""),[to,setTo]=useState(dates.at(-1)||""),[selectedTreatments,setSelectedTreatments]=useState<string[]>([]),[groupBy,setGroupBy]=useState<"plot"|"treatment">("plot"),[result,setResult]=useState<ComparisonResult>(),[error,setError]=useState("");
  const [activeItem,setActiveItem]=useState<ChartItemDetail>();
  const request=useMemo<ComparisonRequest>(()=>({mode,sessionIds,from,to,selectedTreatments:selectedTreatments.length?selectedTreatments:undefined,groupBy,aggregation:"average"}),[mode,sessionIds,from,to,selectedTreatments,groupBy]);
  const valid=mode==="sessions"?sessionIds.length>=2:Boolean(from&&to&&from<=to);
  useEffect(()=>{if(!valid){setResult(undefined);onSelectionChange(undefined);return}let active=true;setError("");compareObservation(projectId,type.id,request).then(data=>{if(active){setResult(data);onSelectionChange(request)}}).catch(e=>{if(active){setError(e instanceof Error?e.message:String(e));setResult(undefined);onSelectionChange(undefined)}});return()=>{active=false}},[projectId,type.id,request,valid,onSelectionChange]);
  const validPoints=result?.points.map((point,index)=>({point,index,key:`entity_${index}`})).filter(({point})=>result?.series.some(series=>point.values[series.key]!=null&&Number.isFinite(Number(point.values[series.key]))))||[];
  const validSeries=result?.series.filter(series=>result.points.some(point=>point.values[series.key]!=null&&Number.isFinite(Number(point.values[series.key]))))||[];
  const lineData=result?.series.map(series=>({label:series.label,...Object.fromEntries(validPoints.map(({point,key})=>[key,point.values[series.key]]))}))||[];
  const barData=result?.points.map(point=>({label:point.category,...point.values}))||[];
  const detail=(entity:string,session:string,value:unknown):ChartItemDetail=>{const record=records.find(x=>x.plotName===entity),point=result?.points.find(x=>x.category===entity),series=result?.series.find(x=>x.label===session||x.key===session);return{name:entity,value:Number(value),observation:groupBy==="treatment"?`Mean ${type.name}`:type.name,unit:type.unit,session:series?.label||session,treatment:groupBy==="treatment"?entity:record?`T${record.treatment}`:undefined,replication:record?`R${record.replication}`:undefined,plot:groupBy==="plot"?entity:undefined,count:groupBy==="treatment"&&series?point?.values[series.key]!=null?records.filter(x=>`T${x.treatment}`===entity&&x.capturedAt.slice(0,10)===graphs.sessions.find(s=>s.label===series.label)?.capturedAt.slice(0,10)).length:undefined:undefined}};
  const lineDot=(entity:string,color:string,index:number)=>(props:any)=>{if(props.value==null||!Number.isFinite(Number(props.value)))return <g/>;const item=detail(entity,String(props.payload?.label||""),props.value);return <circle cx={props.cx} cy={props.cy} r={Math.max(4.5,8-index*.4)} fill={color} stroke="var(--background)" strokeWidth={1.5} {...selectHandlers(setActiveItem,item)}/>};
  const pointShape=(session:string,color:string)=>(props:any)=>{if(props.payload?.value==null)return <g/>;const item=detail(String(props.payload.label),session,props.payload.value);return <circle cx={props.cx} cy={props.cy} r={6} fill={color} stroke="var(--background)" strokeWidth={1.5} {...selectHandlers(setActiveItem,item)}/>};
  const barShape=(session:string)=>(props:any)=>{if(props.value==null)return <g/>;const item=detail(String(props.payload?.label),session,props.value);return <Rectangle {...props} radius={[5,5,0,0]} {...selectHandlers(setActiveItem,item)}/>};
  const lineHit=(entity:string,key:string)=>(...args:any[])=>{const row=nearestChartRow(args.at(-1),lineData);if(row?.[key]!=null)setActiveItem(detail(entity,String(row.label),row[key]))};
  const hitLine=(entity:string,key:string)=><Line key={`hit-${key}`} dataKey={key} stroke="transparent" strokeWidth={14} fill="none" dot={false} activeDot={false} connectNulls={false} legendType="none" isAnimationActive={false} pointerEvents="stroke" data-chart-item="true" onMouseMove={lineHit(entity,key)} onPointerDown={lineHit(entity,key)}/>;
  const chart=chartStyle==="line"?<LineChart data={lineData} data-chart-root="true"><CartesianGrid strokeDasharray="4 4" opacity={.25}/><XAxis dataKey="label"/><YAxis/><Legend/>{validPoints.map(({point,key},i)=><Line key={key} name={point.category} dataKey={key} stroke={colors[i%colors.length]} strokeWidth={3} strokeDasharray={i%2?`${7+i} ${3+i%3}`:undefined} connectNulls={false} dot={lineDot(point.category,colors[i%colors.length],i)} activeDot={lineDot(point.category,colors[i%colors.length],i)}/>)}{validPoints.map(({point,key})=>hitLine(point.category,key))}</LineChart>:chartStyle==="points"?<ScatterChart><CartesianGrid strokeDasharray="4 4" opacity={.25}/><XAxis dataKey="label" type="category"/><YAxis/><Legend/>{validSeries.map((s,i)=><Scatter key={s.key} name={s.label} data={result!.points.flatMap(p=>p.values[s.key]==null?[]:[{label:p.category,value:p.values[s.key]}])} dataKey="value" fill={colors[i%colors.length]} shape={pointShape(s.label,colors[i%colors.length])}/>)}</ScatterChart>:<BarChart data={barData}><CartesianGrid strokeDasharray="4 4" opacity={.25}/><XAxis dataKey="label"/><YAxis/><Legend/>{validSeries.map((s,i)=><Bar key={s.key} dataKey={s.key} name={s.label} fill={colors[i%colors.length]} shape={barShape(s.label)}/>)}</BarChart>;
  return <div><div className="mb-5 rounded-2xl border bg-secondary/20 p-4"><div className="flex flex-wrap items-center gap-3"><span className="text-sm font-medium">Compare</span><select value={mode} onChange={e=>setMode(e.target.value as typeof mode)} className="rounded-full border bg-background px-4 py-2"><option value="sessions">Two or more sessions</option><option value="dateRange">Date range</option></select><span className="text-sm font-medium">Show</span><div className="inline-flex rounded-full border bg-background p-1">{(["plot","treatment"] as const).map(x=><button key={x} onClick={()=>setGroupBy(x)} className={`rounded-full px-4 py-1.5 capitalize ${groupBy===x?"bg-primary text-primary-foreground":""}`}>{x==="plot"?"Replications / plots":"Treatment means"}</button>)}</div></div><div className="mt-4 flex flex-wrap items-center gap-2"><span className="text-sm font-medium">Treatments</span>{treatments.map(x=><label key={x} className={`cursor-pointer rounded-full border px-3 py-2 text-sm ${selectedTreatments.includes(x)?"border-primary bg-primary/10":"bg-background"}`}><input type="checkbox" className="mr-2" checked={selectedTreatments.includes(x)} onChange={()=>setSelectedTreatments(toggle(selectedTreatments,x))}/>{x}</label>)}<span className="text-xs text-muted-foreground">None means all.</span></div>{mode==="sessions"?<div className="mt-4 flex flex-wrap gap-2">{graphs.sessions.map(s=><label key={s.id} className={`cursor-pointer rounded-full border px-3 py-2 text-sm ${sessionIds.includes(s.id)?"border-primary bg-primary/10":"bg-background"}`}><input type="checkbox" className="mr-2" checked={sessionIds.includes(s.id)} onChange={()=>setSessionIds(toggle(sessionIds,s.id))}/>{s.label}</label>)}</div>:<div className="mt-4 flex gap-3"><label className="text-xs text-muted-foreground">From<InputDate value={from} set={setFrom}/></label><label className="text-xs text-muted-foreground">To<InputDate value={to} set={setTo}/></label></div>}{!valid&&<p className="mt-3 text-sm text-muted-foreground">Choose at least two sessions or a valid range.</p>}</div>{error&&<div className="rounded-2xl border border-destructive/40 p-5 text-destructive">{error}</div>}{result&&<div className="glass-card p-5"><h3 className="font-semibold">{result.title}</h3><p className="mb-4 text-sm text-muted-foreground">Every value is constructed from plot-level records and persisted layout relationships.</p><div className="h-80"><InteractiveChart tooltip={activeItem} clear={()=>setActiveItem(undefined)}><ResponsiveContainer>{chart}</ResponsiveContainer></InteractiveChart></div></div>}</div>;
}
function InputDate({value,set}:{value:string;set:(value:string)=>void}){return <input type="date" value={value} onChange={e=>set(e.target.value)} className="mt-1 block rounded-lg border bg-background px-3 py-2 text-foreground"/>}
