import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Download, Pencil, Plus, Trash2 } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, Rectangle, ResponsiveContainer, Scatter, ScatterChart, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { ObservationMeasurement, ObservationType } from "@/types/observation";
import { deleteObservationRecord, exportObservations, getObservationGraphs, getObservationSummary, listObservationRecords, listObservationTypes, updateObservationRecord, type ComparisonRequest, type ObservationGraphs, type ObservationSummary } from "@/services/observations";
import { useToast } from "@/hooks/use-toast";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import ComparisonPanel from "./ComparisonPanel";
import ChartExportDialog from "./ChartExportDialog";
import { InteractiveChart, selectHandlers, type ChartItemDetail } from "./ChartInteraction";

export type ChartStyle="line"|"bar"|"points";
const colors=["#2fbfa9","#3978c5","#e29b3f","#9b62c7","#d35f78","#58756f","#ef7f45","#466eab","#79a84b","#a85d8c"];
const fmt=(n:number|null)=>n==null?"—":Number.isInteger(n)?String(n):n.toFixed(1);

const nearestChartRow=(event:any,rows:Array<Record<string,any>>)=>{const native=event?.nativeEvent||event,target=native?.currentTarget||native?.target,root=target?.closest?.("[data-chart-root]");if(!root||!rows.length)return rows[0];const ticks=[...root.querySelectorAll(".recharts-xAxis .recharts-cartesian-axis-tick")];if(!ticks.length)return rows[0];const x=Number(native.clientX),index=ticks.reduce((best:number,tick:any,i:number)=>Math.abs(tick.getBoundingClientRect().left+tick.getBoundingClientRect().width/2-x)<Math.abs((ticks[best] as any).getBoundingClientRect().left+(ticks[best] as any).getBoundingClientRect().width/2-x)?i:best,0);return rows[Math.min(index,rows.length-1)]};

export default function ObservationDetailsPage(){
  const {projectId="",typeId=""}=useParams(),navigate=useNavigate(),{toast}=useToast();
  const [tab,setTab]=useState<"data"|"graphs"|"summary">("data"),[graphMode,setGraphMode]=useState<"straight"|"comparison">("straight"),[chartStyle,setChartStyle]=useState<ChartStyle>("bar");
  const [type,setType]=useState<ObservationType>(),[values,setValues]=useState<ObservationMeasurement[]>([]),[summary,setSummary]=useState<ObservationSummary>(),[graphs,setGraphs]=useState<ObservationGraphs>(),[editing,setEditing]=useState<string>();
  const [sessionId,setSessionId]=useState(""),[treatmentId,setTreatmentId]=useState(""),[range,setRange]=useState(false),[comparison,setComparison]=useState<ComparisonRequest>(),[chartExportOpen,setChartExportOpen]=useState(false);
  const [activeItem,setActiveItem]=useState<ChartItemDetail>();
  const selectComparison=useCallback((value?:ComparisonRequest)=>setComparison(value),[]);
  const load=async()=>{try{const [types,records]=await Promise.all([listObservationTypes(projectId),listObservationRecords(projectId,typeId)]);const current=types.find(x=>x.id===typeId);setType(current);setValues(records);if(current?.dataType==="number"){const[s,g]=await Promise.all([getObservationSummary(projectId,typeId),getObservationGraphs(projectId,typeId)]);setSummary(s);setGraphs(g);setSessionId(x=>x||g.sessions.at(-1)?.id||"")}}catch(e){toast({title:"Unable to load observation",description:e instanceof Error?e.message:String(e),variant:"destructive"})}};
  useEffect(()=>{void load()},[projectId,typeId]);
  useEffect(()=>{if(chartExportOpen&&tab!=="graphs")setTab("graphs")},[chartExportOpen,tab]);
  const update=async(v:ObservationMeasurement,next:string)=>{try{await updateObservationRecord({projectId,recordId:v.id,value:type?.dataType==="number"?Number(next):type?.dataType==="boolean"?next==="true":next});setEditing(undefined);await load()}catch(e){toast({title:"Update failed",description:e instanceof Error?e.message:String(e),variant:"destructive"})}};
  const remove=async(id:string)=>{try{await deleteObservationRecord(projectId,id);await load()}catch(e){toast({title:"Delete failed",description:e instanceof Error?e.message:String(e),variant:"destructive"})}};
  const selectedSession=graphs?.sessions.find(x=>x.id===sessionId)||graphs?.sessions.at(-1);
  const straightSeries=useMemo(()=>treatmentId?graphs?.timeSeries.filter(x=>x.treatmentId===treatmentId)||[]:graphs?.treatmentSeries||[],[graphs,treatmentId]);
  const straightData=useMemo(()=>{if(!graphs)return[];if(range)return graphs.sessions.map(s=>({label:s.label,...Object.fromEntries(straightSeries.map(series=>["treatment" in series?series.treatment:series.replication,series.values.find(v=>v.sessionId===s.id)?.value??null]))}));const session=selectedSession;return straightSeries.map(series=>{const key="treatment" in series?series.treatment:series.replication;return{label:key,value:series.values.find(v=>v.sessionId===session?.id)?.value??null}})},[graphs,range,selectedSession,straightSeries]);
  if(!type)return <div className="p-6 text-muted-foreground">Loading observation…</div>;
  const seriesKeys=range?straightSeries.filter(series=>series.values.some(value=>value.value!=null&&Number.isFinite(Number(value.value)))).map(x=>"treatment" in x?x.treatment:x.replication):[];
  const detail=(key:string,label:string,value:unknown):ChartItemDetail=>{const resolvedKey=key==="Value"?label:key,series=straightSeries.find(x=>("treatment" in x?x.treatment:x.replication)===resolvedKey),numeric=Number(value),session=range?label:selectedSession?.label;return{name:resolvedKey,value:numeric,observation:type.name,unit:type.unit,session,treatment:"treatment" in (series||{})?(series as any).treatment:series?`T${series.treatmentId}`:undefined,replication:"replication" in (series||{})?(series as any).replication:undefined,plot:"plot" in (series||{})?(series as any).plot:undefined,count:"treatment" in (series||{})?(series as any).values.find((v:any)=>v.sessionId===(range?graphs?.sessions.find(s=>s.label===label)?.id:selectedSession?.id))?.count:undefined}};
  const lineDot=(key:string,color:string,index:number)=>(props:any)=>{if(props.value==null||!Number.isFinite(Number(props.value)))return <g/>;const item=detail(key,String(props.payload?.label||""),props.value);return <circle cx={props.cx} cy={props.cy} r={Math.max(4.5,8-index*.4)} fill={color} stroke="var(--background)" strokeWidth={1.5} {...selectHandlers(setActiveItem,item)}/>};
  const pointShape=(key:string,color:string)=>(props:any)=>{if(props.payload?.value==null)return <g/>;const item=detail(key,String(props.payload.label),props.payload.value);return <circle cx={props.cx} cy={props.cy} r={6} fill={color} stroke="var(--background)" strokeWidth={1.5} {...selectHandlers(setActiveItem,item)}/>};
  const barShape=(key:string)=>(props:any)=>{if(props.value==null)return <g/>;const item=detail(key,String(props.payload?.label),props.value);return <Rectangle {...props} radius={[6,6,0,0]} {...selectHandlers(setActiveItem,item)}/>};
  const lineHit=(key:string)=>(...args:any[])=>{const row=nearestChartRow(args.at(-1),straightData);if(row?.[key]!=null)setActiveItem(detail(key,String(row.label),row[key]))};
  const hitLine=(key:string)=><Line key={`hit-${key}`} dataKey={key} stroke="transparent" strokeWidth={14} fill="none" dot={false} activeDot={false} connectNulls={false} legendType="none" isAnimationActive={false} pointerEvents="stroke" data-chart-item="true" onMouseMove={lineHit(key)} onPointerDown={lineHit(key)}/>;
  const chart=chartStyle==="line"?<LineChart data={straightData} data-chart-root="true"><CartesianGrid strokeDasharray="4 4" opacity={.25}/><XAxis dataKey="label"/><YAxis/><Legend/>{seriesKeys.length?seriesKeys.map((key,i)=><Line key={key} name={key} dataKey={key} stroke={colors[i%colors.length]} strokeWidth={3} strokeDasharray={i%2?`${7+i} ${3+i%3}`:undefined} connectNulls={false} dot={lineDot(key,colors[i%colors.length],i)} activeDot={lineDot(key,colors[i%colors.length],i)}/>):<Line dataKey="value" stroke={colors[0]} strokeWidth={3} connectNulls={false} dot={lineDot("Value",colors[0],0)} activeDot={lineDot("Value",colors[0],0)}/>} {seriesKeys.length?seriesKeys.map(hitLine):hitLine("value")}</LineChart>:chartStyle==="points"?<ScatterChart><CartesianGrid strokeDasharray="4 4" opacity={.25}/><XAxis dataKey="label" type="category"/><YAxis/><Legend/>{seriesKeys.length?seriesKeys.map((key,i)=><Scatter key={key} name={key} data={straightData.filter(row=>row[key]!=null).map(row=>({label:row.label,value:row[key]}))} dataKey="value" fill={colors[i%colors.length]} shape={pointShape(key,colors[i%colors.length])}/>):<Scatter data={straightData.filter(row=>row.value!=null)} dataKey="value" fill={colors[0]} shape={pointShape("Value",colors[0])}/>}</ScatterChart>:<BarChart data={straightData}><CartesianGrid strokeDasharray="4 4" opacity={.25}/><XAxis dataKey="label"/><YAxis/><Legend/>{seriesKeys.length?seriesKeys.map((key,i)=><Bar key={key} dataKey={key} name={key} fill={colors[i%colors.length]} shape={barShape(key)}/>):<Bar dataKey="value" fill={colors[0]} shape={barShape("Value")}/>}</BarChart>;
  const straightChart={title:treatmentId?`T${treatmentId} replication plots`:"Treatment overview",subtitle:treatmentId?"Each series remains attached to this treatment through its plot ID.":"Means are calculated from plot-level observations."};
  const CanonicalChart=(_props:{data:unknown;observation:string;unit?:string;active?:ChartItemDetail;setActive:(item?:ChartItemDetail)=>void})=> <InteractiveChart tooltip={activeItem} clear={()=>setActiveItem(undefined)}><ResponsiveContainer>{chart}</ResponsiveContainer></InteractiveChart>;
  return <div className="safe-bottom p-4 sm:p-8"><div className="mb-8 flex flex-wrap items-start justify-between gap-4"><div><button onClick={()=>navigate(`/projects/${projectId}`)} className="mb-3 flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4"/>Project</button><h1 className="text-3xl font-bold">{type.name}</h1><p className="text-muted-foreground">{values.length} values{type.unit?` · ${type.unit}`:""}</p></div><div className="flex gap-2"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline"><Download/>Export</Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>void exportObservations(projectId,"csv",typeId)}>CSV</DropdownMenuItem><DropdownMenuItem onClick={()=>void exportObservations(projectId,"xlsx",typeId,comparison)}>Excel</DropdownMenuItem><DropdownMenuItem onClick={()=>void exportObservations(projectId,"pdf",typeId,comparison)}>PDF</DropdownMenuItem><DropdownMenuItem onClick={()=>setChartExportOpen(true)}>Charts</DropdownMenuItem></DropdownMenuContent></DropdownMenu><Button onClick={()=>navigate(`/projects/${projectId}`,{state:{quickObservationType:typeId}})}><Plus/>Record</Button></div></div>
  <div className="mb-7 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Records",summary?.count??values.length],["Average",fmt(summary?.average??null)],["Minimum",fmt(summary?.minimum??null)],["Maximum",fmt(summary?.maximum??null)]].map(([l,v])=><div key={l} className="glass-card p-5"><p className="text-xs uppercase text-muted-foreground">{l}</p><p className="mt-2 text-3xl font-bold">{v}</p></div>)}</div>
  <div className="mb-7 inline-flex rounded-full border p-1">{(["data","graphs","summary"] as const).map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-full px-5 py-2 capitalize ${tab===x?"bg-primary text-primary-foreground":""}`}>{x}</button>)}</div>
  {tab==="data"&&<div className="overflow-x-auto rounded-3xl border"><table className="w-full min-w-[900px] text-left"><thead className="bg-secondary/40 text-xs uppercase text-muted-foreground"><tr>{["Date / time","Plot","Treatment","Replication","Value","Note",""].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{values.map(v=><tr key={v.id} className="border-t"><td className="p-4">{new Date(v.capturedAt).toLocaleString()}</td><td className="p-4 font-semibold">{v.plotName}</td><td className="p-4">T{v.treatment}</td><td className="p-4">R{v.replication}</td><td className="p-4">{editing===v.id?<Input autoFocus defaultValue={String(v.value)} onKeyDown={e=>{if(e.key==="Enter")void update(v,e.currentTarget.value)}} onBlur={e=>void update(v,e.target.value)} className="w-28"/>:<>{String(v.value)} <span className="text-muted-foreground">{v.unit}</span></>}</td><td className="p-4">{v.note}</td><td className="p-4"><button onClick={()=>setEditing(v.id)}><Pencil className="h-4 w-4"/></button><button onClick={()=>void remove(v.id)} className="ml-4 text-destructive"><Trash2 className="h-4 w-4"/></button></td></tr>)}</tbody></table></div>}
  {tab==="graphs"&&(type.dataType==="number"&&graphs?<div><div className="mb-5 flex flex-wrap items-center gap-3"><div className="inline-flex rounded-full border p-1">{(["straight","comparison"] as const).map(x=><button key={x} onClick={()=>setGraphMode(x)} className={`rounded-full px-5 py-2 capitalize ${graphMode===x?"bg-primary text-primary-foreground":""}`}>{x}</button>)}</div><span className="ml-auto text-sm text-muted-foreground">Chart</span><div className="inline-flex rounded-full border p-1">{(["line","bar","points"] as const).map(x=><button key={x} onClick={()=>setChartStyle(x)} className={`rounded-full px-4 py-2 capitalize ${chartStyle===x?"bg-primary text-primary-foreground":""}`}>{x}</button>)}</div></div>{graphMode==="straight"?<><div className="mb-4 flex flex-wrap gap-3 rounded-2xl border bg-secondary/20 p-4"><label className="text-sm">View <select value={treatmentId} onChange={e=>setTreatmentId(e.target.value)} className="ml-2 rounded-full border bg-background px-3 py-2"><option value="">Treatment overview</option>{graphs.treatmentSeries.map(x=><option key={x.treatmentId} value={x.treatmentId}>{x.treatment} replications</option>)}</select></label><label className="text-sm">Period <select value={range?"range":"session"} onChange={e=>{const next=e.target.value==="range";setRange(next);setChartStyle(next?"line":"bar")}} className="ml-2 rounded-full border bg-background px-3 py-2"><option value="session">One session</option><option value="range">All sessions</option></select></label>{!range&&<select value={selectedSession?.id||""} onChange={e=>setSessionId(e.target.value)} className="rounded-full border bg-background px-3 py-2">{graphs.sessions.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select>}</div>{straightChart&&<div className="glass-card p-5"><h3 className="font-semibold">{straightChart.title}</h3><p className="mb-4 text-sm text-muted-foreground">{straightChart.subtitle}</p><div className="h-80"><CanonicalChart data={straightChart} observation={type.name} unit={type.unit} active={activeItem} setActive={setActiveItem}/></div></div>}</>:<ComparisonPanel projectId={projectId} type={type} records={values} graphs={graphs} chartStyle={chartStyle} onSelectionChange={selectComparison}/>}</div>:<div>Graphs are available for numeric observations.</div>)}
  <ChartExportDialog open={chartExportOpen} onOpenChange={setChartExportOpen} projectId={projectId} initialTypeId={type.id}/>{tab==="summary"&&<div className="glass-card p-6"><h3 className="text-lg font-semibold">By treatment</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{summary?.byTreatment.map(x=><div key={x.treatment} className="rounded-xl border p-4"><b>{x.treatment}</b><p className="text-sm text-muted-foreground">N {x.count} · Mean {fmt(x.average)} · Min {fmt(x.minimum)} · Max {fmt(x.maximum)}</p></div>)}</div></div>}</div>;
}
