import { api } from "@/services/api";
import type { ObservationDataType, ObservationMeasurement, ObservationType } from "@/types/observation";

type ApiType = Omit<ObservationType, "id" | "lastUsedAt"> & { _id: string; updatedAt: string };
type ApiRecord = Omit<ObservationMeasurement, "id" | "plotName" | "treatment" | "replication" | "unit"> & { _id: string; plotName?: string; treatment?: number; replication?: number; unit?: string };
const unwrap = <T,>(payload: any): T => (payload?.data ?? payload) as T;
const mapType = (x: ApiType): ObservationType => ({ ...x, id: x._id, lastUsedAt: x.updatedAt });
const mapRecord = (x: ApiRecord): ObservationMeasurement => ({ ...x, id: x._id, plotName: x.plotName || "Unknown plot", treatment: x.treatment ?? 0, replication: x.replication ?? 0 });
type CachedRead={expires:number;value?:unknown;promise?:Promise<unknown>};
const readCache=new Map<string,CachedRead>(),readTtlMs=2_000;
const cachedRead=<T,>(key:string,load:()=>Promise<T>):Promise<T>=>{const now=Date.now(),cached=readCache.get(key);if(cached?.promise)return cached.promise as Promise<T>;if(cached?.value!==undefined&&cached.expires>now)return Promise.resolve(cached.value as T);const promise=load().then(value=>{readCache.set(key,{value,expires:Date.now()+readTtlMs});return value},error=>{readCache.delete(key);throw error});readCache.set(key,{promise,expires:now+readTtlMs});return promise};
const invalidateObservationReads=(projectId:string)=>{for(const key of readCache.keys())if(key.includes(`:${projectId}:`)||key.endsWith(`:${projectId}`))readCache.delete(key)};

export async function listObservationTypes(projectId: string) { return cachedRead(`types:${projectId}`,async()=>unwrap<ApiType[]>((await api.get("/observations/types", { params: { projectId } })).data).map(mapType)); }
export async function createObservationType(payload: { projectId: string; name: string; dataType: ObservationDataType; unit?: string }) { const value=mapType(unwrap<ApiType>((await api.post("/observations/types", payload)).data));invalidateObservationReads(payload.projectId);return value; }
export async function listObservationRecords(projectId: string, observationTypeId?: string) { return cachedRead(`records:${projectId}:${observationTypeId||"all"}`,async()=>unwrap<ApiRecord[]>((await api.get("/observations/records", { params: { projectId, observationTypeId } })).data).map(mapRecord)); }
export async function createObservationRecord(payload: { projectId: string; plotId: string; observationTypeId: string; value: number|string|boolean; note?: string; capturedAt?: string }) { const value=mapRecord(unwrap<ApiRecord>((await api.post("/observations/records", payload)).data));invalidateObservationReads(payload.projectId);return value; }
export async function bulkCreateObservationRecords(payload: { projectId: string; observationTypeId: string; records: Array<{ plotId: string; value: number|string|boolean; note?: string; capturedAt?: string }> }) { const value=unwrap<ApiRecord[]>((await api.post("/observations/records/bulk", payload)).data).map(mapRecord);invalidateObservationReads(payload.projectId);return value; }
export async function updateObservationRecord(payload: { projectId: string; recordId: string; value?: number|string|boolean; note?: string; capturedAt?: string }) { const value=mapRecord(unwrap<ApiRecord>((await api.patch("/observations/records", payload)).data));invalidateObservationReads(payload.projectId);return value; }
export async function deleteObservationRecord(projectId: string, recordId: string) { await api.delete("/observations/records", { data: { projectId, recordId } });invalidateObservationReads(projectId); }
export interface ObservationSummary { average: number|null; minimum: number|null; maximum: number|null; count: number; byTreatment: Array<{ treatment:string; average:number; minimum:number; maximum:number; count:number }> }
export interface ObservationGraphSession { id:string; label:string; capturedAt:string; round:number; comparePlots:Array<{plotId:string;plot:string;treatmentId:string;replicationId:string;value:number}>; compareTreatments:Array<{treatmentId:string;treatment:string;average:number;minimum:number;maximum:number;count:number}> }
export interface ObservationGraphs { sessions:ObservationGraphSession[]; treatmentSeries:Array<{treatmentId:string;treatment:string;values:Array<{sessionId:string;session:string;capturedAt:string;value:number|null;count:number}>}>; timeSeries:Array<{plotId:string;plot:string;treatmentId:string;replicationId:string;replication:string;values:Array<{sessionId:string;session:string;capturedAt:string;value:number}>}> }
export interface ComparisonRequest { mode:"specificDates"|"dateRange"|"sessions"|"time"; selectedDates?:string[]; from?:string; to?:string; sessionIds?:string[]; timeFrom?:string; timeTo?:string; selectedPlots?:string[]; selectedTreatments?:string[]; groupBy?:"plot"|"treatment"; aggregation?:"average"|"minimum"|"maximum"|"growth"|"minMax"|"daily" }
export interface ComparisonResult { title:string; chartType:"groupedBar"|"line"; xAxis:string; yAxis:string; series:Array<{key:string;label:string}>; points:Array<{category:string;values:Record<string,number|null>;ranges?:Record<string,{minimum:number;maximum:number}|null>;change?:{previous:number;current:number;absolute:number;percentage:number|null}}> }
export async function getObservationSummary(projectId:string,observationTypeId:string){return cachedRead(`summary:${projectId}:${observationTypeId}`,async()=>unwrap<ObservationSummary>((await api.get("/observations/summary",{params:{projectId,observationTypeId}})).data))}
export async function getObservationGraphs(projectId:string,observationTypeId:string){return cachedRead(`graphs:${projectId}:${observationTypeId}`,async()=>unwrap<ObservationGraphs>((await api.get("/observations/graphs",{params:{projectId,observationTypeId}})).data))}
export async function compareObservation(projectId:string,observationTypeId:string,request:ComparisonRequest){return unwrap<ComparisonResult>((await api.post("/observations/compare",{projectId,observationTypeId,...request})).data)}
export async function exportObservations(projectId:string,format:"csv"|"xlsx"|"pdf",observationTypeId?:string,comparison?:ComparisonRequest){const response=await api.get("/observations/export",{params:{projectId,observationTypeId,format,comparison:comparison?JSON.stringify(comparison):undefined},responseType:"blob"});const disposition=response.headers["content-disposition"]||"";const name=/filename="?([^";]+)"?/.exec(disposition)?.[1]||`project-observations.${format}`;const url=URL.createObjectURL(response.data);const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
export async function exportSelectedCharts(projectId:string,format:"png"|"pdf"|"xlsx",charts:Array<{title:string;subtitle?:string;svg:string;columns:string[];rows:Array<Array<string|number|null>>}>){const response=await api.post("/observations/export/charts",{projectId,format,charts},{responseType:"blob"});const url=URL.createObjectURL(response.data),a=document.createElement("a");a.href=url;a.download=`observation-charts.${format}`;a.click();URL.revokeObjectURL(url)}
