export const SYNC_TABLE_SCHEMAS: string[] = [
  `CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    location TEXT,
    replications_count INTEGER NOT NULL DEFAULT 0,
    treatments_count INTEGER NOT NULL DEFAULT 0,
    plots_count INTEGER NOT NULL DEFAULT 0,
    notes_count INTEGER NOT NULL DEFAULT 0,
    server_version INTEGER NOT NULL DEFAULT 1,
    last_modified_by_device_id TEXT NOT NULL DEFAULT 'local-device',
    synced_at TEXT,
    created_offline_at TEXT,
    sync_status TEXT NOT NULL DEFAULT 'local_only',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS plots (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    title TEXT NOT NULL,
    color TEXT,
    replication INTEGER NOT NULL,
    treatment INTEGER NOT NULL,
    plot_index TEXT NOT NULL,
    notes_count INTEGER NOT NULL DEFAULT 0,
    server_version INTEGER NOT NULL DEFAULT 1,
    last_modified_by_device_id TEXT NOT NULL DEFAULT 'local-device',
    synced_at TEXT,
    created_offline_at TEXT,
    sync_status TEXT NOT NULL DEFAULT 'local_only',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS notes (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    plot_id TEXT NOT NULL,
    title TEXT,
    content_json TEXT NOT NULL,
    photo_ids_json TEXT,
    is_conflict INTEGER NOT NULL DEFAULT 0,
    conflict_group_id TEXT,
    conflict_reason TEXT,
    server_version INTEGER NOT NULL DEFAULT 1,
    last_modified_by_device_id TEXT NOT NULL DEFAULT 'local-device',
    synced_at TEXT,
    created_offline_at TEXT,
    sync_status TEXT NOT NULL DEFAULT 'local_only',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS ideas (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    idea TEXT NOT NULL,
    date TEXT NOT NULL,
    is_conflict INTEGER NOT NULL DEFAULT 0,
    conflict_group_id TEXT,
    conflict_reason TEXT,
    server_version INTEGER NOT NULL DEFAULT 1,
    last_modified_by_device_id TEXT NOT NULL DEFAULT 'local-device',
    synced_at TEXT,
    created_offline_at TEXT,
    sync_status TEXT NOT NULL DEFAULT 'local_only',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS outbox_ops (
    op_id TEXT PRIMARY KEY NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    action TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'pending',
    policy_preserve_history INTEGER NOT NULL DEFAULT 0,
    policy_collapse_updates INTEGER NOT NULL DEFAULT 0,
    policy_preserve_conflicts INTEGER NOT NULL DEFAULT 0,
    policy_hard_delete INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS sync_conflicts (
    conflict_id TEXT PRIMARY KEY NOT NULL,
    op_id TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    reason TEXT NOT NULL,
    local_payload_json TEXT,
    server_snapshot_json TEXT,
    resolved INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS sync_state (
    key TEXT PRIMARY KEY NOT NULL,
    value TEXT
  );`,
  `CREATE TABLE IF NOT EXISTS photo_upload_queue (
    photo_id TEXT PRIMARY KEY NOT NULL,
    idempotency_key TEXT NOT NULL,
    local_path TEXT NOT NULL,
    original_name TEXT,
    mime_type TEXT,
    project_id TEXT NOT NULL,
    plot_id TEXT NOT NULL,
    note_id TEXT,
    captured_at TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    retry_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    uploaded_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS local_photos (
    photo_id TEXT PRIMARY KEY NOT NULL,
    local_path TEXT,
    original_name TEXT,
    mime_type TEXT,
    project_id TEXT,
    plot_id TEXT,
    note_id TEXT,
    cloud_json TEXT,
    upload_status TEXT,
    captured_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE INDEX IF NOT EXISTS idx_outbox_status_created_at ON outbox_ops(status, created_at);`,
  `CREATE INDEX IF NOT EXISTS idx_photo_upload_queue_status ON photo_upload_queue(status, updated_at);`,
  `CREATE INDEX IF NOT EXISTS idx_local_photos_project ON local_photos(project_id, plot_id, note_id);`,
  `CREATE INDEX IF NOT EXISTS idx_projects_user ON projects(user_id);`,
  `CREATE INDEX IF NOT EXISTS idx_plots_project ON plots(project_id);`,
  `CREATE INDEX IF NOT EXISTS idx_notes_plot ON notes(plot_id);`,
  `CREATE INDEX IF NOT EXISTS idx_ideas_date ON ideas(date);`,
];
