import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Check, Hash, Plus, Type, X } from "lucide-react";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import type { PlotDto } from "@/services/projects";
import type { ObservationDataType, ObservationType } from "@/types/observation";
import { bulkCreateObservationRecords, createObservationRecord, createObservationType, listObservationTypes } from "@/services/observations";
import { useToast } from "@/hooks/use-toast";

type Step = "pick" | "new" | "mode" | "capture";
type Pending = { plotId:string; value:number|string|boolean; note?:string; capturedAt:string };
export function QuickObservationDialog({ open, onOpenChange, projectId, plots, onSaved }: { open:boolean; onOpenChange:(v:boolean)=>void; projectId:string; plots:PlotDto[]; onSaved?:()=>void }) {
  const { toast }=useToast(); const [step,setStep]=useState<Step>("pick"); const [types,setTypes]=useState<ObservationType[]>([]); const [selected,setSelected]=useState<ObservationType>();
  const [name,setName]=useState(""); const [dataType,setDataType]=useState<ObservationDataType>("number"); const [unit,setUnit]=useState(""); const [mode,setMode]=useState<"single"|"run">("run"); const [plotIndex,setPlotIndex]=useState(0); const [singlePlot,setSinglePlot]=useState(""); const [value,setValue]=useState(""); const [note,setNote]=useState(""); const [pending,setPending]=useState<Pending[]>([]); const [saving,setSaving]=useState(false); const inputRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{if(open)listObservationTypes(projectId).then(setTypes).catch(e=>toast({title:"Unable to load observations",description:e.message,variant:"destructive"}))},[open,projectId,toast]);
  useEffect(()=>{if(step==="capture")setTimeout(()=>inputRef.current?.focus(),80)},[step,plotIndex]);
  const close=()=>{onOpenChange(false);setTimeout(()=>{setStep("pick");setSelected(undefined);setValue("");setNote("");setPending([])},200)};
  const create=async()=>{if(!name.trim()||saving)return;setSaving(true);try{const next=await createObservationType({projectId,name:name.trim(),dataType,unit:dataType==="number"?unit.trim():undefined});setTypes(x=>[next,...x]);setSelected(next);setStep("mode")}catch(e){toast({title:"Could not create observation",description:e instanceof Error?e.message:String(e),variant:"destructive"})}finally{setSaving(false)}};
  const currentPlot=mode==="run"?plots[plotIndex]:plots.find(p=>p._id===singlePlot);
  const parsed=()=>selected?.dataType==="number"?Number(value):selected?.dataType==="boolean"?value==="true":value;
  const save=async(advance=false)=>{if(!selected||!currentPlot||value===""||saving)return;const next={plotId:currentPlot._id,value:parsed(),note:note.trim()||undefined,capturedAt:new Date().toISOString()};if(mode==="run"&&advance&&plotIndex<plots.length-1){setPending(x=>[...x,next]);setPlotIndex(i=>i+1);setValue("");setNote("");return}setSaving(true);try{if(mode==="run")await bulkCreateObservationRecords({projectId,observationTypeId:selected.id,records:[...pending,next]});else await createObservationRecord({projectId,observationTypeId:selected.id,...next});toast({title:"Observation saved"});onSaved?.();close()}catch(e){toast({title:"Could not save observation",description:e instanceof Error?e.message:String(e),variant:"destructive"})}finally{setSaving(false)}};
  const skip=async()=>{if(plotIndex<plots.length-1){setPlotIndex(i=>i+1);setValue("");setNote("");return}if(!selected||!pending.length){close();return}setSaving(true);try{await bulkCreateObservationRecords({projectId,observationTypeId:selected.id,records:pending});toast({title:"Observations saved"});onSaved?.();close()}catch(e){toast({title:"Could not save observations",description:e instanceof Error?e.message:String(e),variant:"destructive"})}finally{setSaving(false)}};
  const back=()=>setStep(step==="capture"?"mode":"pick");
  return <Dialog open={open} onOpenChange={v=>!v&&close()}><DialogContent className="max-h-[92vh] overflow-y-auto border-border bg-card p-0 sm:max-w-[640px]"><div className="p-6 sm:p-8"><div className="mb-6 flex items-start justify-between"><div><DialogTitle className="text-2xl">{step==="pick"?"What are you recording?":step==="new"?"New observation":step==="mode"?selected?.name:`${selected?.name}${selected?.unit?` · ${selected.unit}`:""}`}</DialogTitle><p className="mt-1 text-muted-foreground">{step==="pick"?"Pick an observation you use in this project, or create a new one.":step==="new"?"Saved to this project and reusable next time.":step==="mode"?"How would you like to capture data?":mode==="run"?`Plot ${plotIndex+1} of ${plots.length}`:"Record one plot"}</p></div><button onClick={close}><X className="h-5 w-5 text-muted-foreground"/></button></div>
  {step==="pick"&&<div className="space-y-3">{types.map(t=><button key={t.id} onClick={()=>{setSelected(t);setStep("mode")}} className="flex w-full items-center justify-between rounded-3xl border bg-secondary/25 p-5 text-left hover:bg-secondary"><span><b className="block text-lg">{t.name}</b><small className="text-muted-foreground">{t.dataType==="boolean"?"Yes / No":t.dataType[0].toUpperCase()+t.dataType.slice(1)}{t.unit?` · ${t.unit}`:""}</small></span><ArrowRight/></button>)}<button onClick={()=>setStep("new")} className="flex w-full items-center gap-3 rounded-3xl border border-dashed p-5 text-lg font-semibold text-primary"><Plus/>New observation</button></div>}
  {step==="new"&&<div className="space-y-6"><div><Label>Observation name</Label><Input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Plant Height" className="mt-2 h-14 rounded-2xl"/></div><div><Label>Data type</Label><div className="mt-2 grid grid-cols-3 gap-3">{([['number',Hash,'Number'],['text',Type,'Text'],['boolean',Check,'Yes / No']] as const).map(([v,I,l])=><button key={v} onClick={()=>setDataType(v)} className={`rounded-2xl border p-4 ${dataType===v?'border-primary bg-primary/10 text-primary':''}`}><I className="mx-auto mb-2"/>{l}</button>)}</div></div>{dataType==="number"&&<div><Label>Unit <span className="text-muted-foreground">(optional)</span></Label><Input value={unit} onChange={e=>setUnit(e.target.value)} placeholder="cm, kg, %, count" className="mt-2 h-14 rounded-2xl"/></div>}<div className="flex justify-between"><Button variant="ghost" onClick={back}><ArrowLeft/>Back</Button><Button onClick={create} disabled={!name.trim()||saving}>{saving?"Saving...":"Continue"}</Button></div></div>}
  {step==="mode"&&<div className="space-y-3"><button onClick={()=>{setMode("run");setPlotIndex(0);setPending([]);setStep("capture")}} className="w-full rounded-3xl border bg-secondary/25 p-5 text-left"><b className="text-lg">Run through plots</b><p className="text-sm text-muted-foreground">Move through all {plots.length} plots in order</p></button><button onClick={()=>{setMode("single");setSinglePlot(plots[0]?._id||"");setStep("capture")}} className="w-full rounded-3xl border bg-secondary/25 p-5 text-left"><b className="text-lg">Single plot</b><p className="text-sm text-muted-foreground">Record one selected plot</p></button><Button variant="ghost" onClick={back}><ArrowLeft/>Back</Button></div>}
  {step==="capture"&&<div className="space-y-5"><div className="rounded-3xl border bg-primary/10 p-5"><span className="text-xs uppercase tracking-widest text-muted-foreground">Current plot</span>{mode==="single"?<select value={singlePlot} onChange={e=>setSinglePlot(e.target.value)} className="mt-2 w-full bg-transparent text-2xl font-bold">{plots.map(p=><option key={p._id} value={p._id}>{p.title}</option>)}</select>:<div className="mt-1 text-3xl font-bold">{currentPlot?.title}</div>}<p className="text-sm text-muted-foreground">Treatment {currentPlot?.treatment} · Replication {currentPlot?.replication}</p></div><div><Label>Value</Label>{selected?.dataType==="boolean"?<div className="mt-2 grid grid-cols-2 gap-3">{["true","false"].map(v=><button key={v} onClick={()=>setValue(v)} className={`h-16 rounded-2xl border text-lg ${value===v?'border-primary bg-primary/10 text-primary':''}`}>{v==="true"?"Yes":"No"}</button>)}</div>:<div className="relative"><Input ref={inputRef} type={selected?.dataType==="number"?"number":"text"} inputMode={selected?.dataType==="number"?"decimal":undefined} value={value} onChange={e=>setValue(e.target.value)} className="mt-2 h-20 rounded-2xl text-3xl"/>{selected?.unit&&<span className="absolute right-5 top-1/2 text-muted-foreground">{selected.unit}</span>}</div>}</div><div><Label>Note <span className="text-muted-foreground">(optional)</span></Label><Input value={note} onChange={e=>setNote(e.target.value)} className="mt-2 h-12 rounded-2xl"/></div><div className="flex flex-wrap justify-between gap-2"><Button variant="ghost" onClick={back}><ArrowLeft/>Back</Button>{mode==="run"?<div className="flex gap-2"><Button variant="outline" disabled={plotIndex===0||saving} onClick={()=>{setPlotIndex(i=>i-1);setPending(x=>x.slice(0,-1))}}>Previous</Button><Button variant="ghost" disabled={saving} onClick={skip}>Skip</Button><Button disabled={value===""||saving} onClick={()=>save(true)}>{saving?"Saving...":plotIndex===plots.length-1?"Finish":"Save & Next"}</Button></div>:<Button disabled={value===""||saving} onClick={()=>save()}>{saving?"Saving...":"Save observation"}</Button>}</div></div>}</div></DialogContent></Dialog>;
}
